<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <UseWpf>true</UseWpf>
    <LangVersion>12</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <Platforms>x86</Platforms>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Playnite/Playnite.csproj" />
    <Compile Include="../Common/*.cs" Link="Common/%(Filename)%(Extension)" />
    <Page Remove="App.xaml;Localization/**/*.xaml" />
    <Content Include="Localization/*.xaml;extension.yaml">
      <TargetPath>BuiltinLibraries/EpicLibrary/%(Identity)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources/**/*;SteamShared/TagLocalization/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../LICENSE.md" Link="BuiltinLibraries/LICENSE.md" CopyToOutputDirectory="PreserveNewest" />
    <Reference Include="System.Web" />
    <Reference Include="System.Management" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

</Project>
